# General redundant packages for removal prior to adding any other roles
required_packages:
  - "exim4"
  
redundant_packages:
  - "bind9*"
  - "postfix*"

users:
  - "daniel"
  - "john"

eximsettings:
  - {question: "dc_smarthost", value: "smtp.mailgun.org:587"}
  - {question: "dc_eximconfig_configtype", value: "smarthost"}
