# Add the keys for repositories
- name: Add repository keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ repository_key_uris }}"

# Add the required repositories.
- name: Add repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ repositories }}"

# Remove unnecessary packages.
- name: Remove unnecessary packages
  apt:
    name: "{{ item }}" 
    state: absent
    autoremove: yes
  with_items: "{{ redundant_packages }}"

# Remove /etc/php5
- name: Remove /etc/php5
  file:
    dest: /etc/php5
    state: absent

# Install all the packages we need. Defined in variables file under required_packages 
- name: Install required packages
  apt:
    name: "{{ item }}" 
    state: present
    update_cache: yes
  with_items: "{{ required_packages }}"

# Rename Vesta directories
- name: Rename Vesta directories
  command: mv "{{ item.src }}" "{{ item.dst }}"
  args:
    creates: "{{ item.dst }}"
  with_items: "{{ vesta_rename_dirs }}"

# Set WEB_BACKEND variable in Vesta configuration
- name: Set Vesta backend configuration
  ini_file:
    dest: /usr/local/vesta/conf/vesta.conf
    section: ''
    option: 'WEB_BACKEND'
    value: "'php7.0-fpm'"
    no_extra_spaces: yes

# Set to listen on PHP7.0
- name: Set to listen on PHP7.0
  replace:
    dest: /usr/local/vesta/data/templates/web/php7.0-fpm/socket.tpl
    regexp: '(\s+)php5-(\s+.*)?$'
    replace: '\1php7.0\2'