# Dotdeb.org repo for PHP-FPM 7.0 
repositories:
  - "deb http://packages.dotdeb.org jessie all"
  - "deb-src http://packages.dotdeb.org jessie all"

# Key URI for Dotdeb.org repo
repository_key_uris:
  - "http://www.dotdeb.org/dotdeb.gpg"

# Redundant Packages for this role
redundant_packages:
  - "*php5*"

# Required packages for this role
required_packages:
  - dpkg-dev
  - libgd2-xpm-dev
  - libgeoip-dev
  - libgeoip1
  - libperl-dev
  - libpcre3
  - libpcre3-dev
  - logrotate
  - geoip-database
  - zip
  - unzip
  - php7.0-memcached
  - memcached
  - php7.0
  - php7.0-xsl
  - php7.0-mbstring
  - php7.0-zip
  - php7.0-bcmath
  - php7.0-common
  - php7.0-cgi
  - php7.0-cli
  - php7.0-phpdbg
  - php7.0-fpm
  - libphp7.0-embed
  - php7.0-dev
  - php7.0-dbg
  - php7.0-curl
  - php7.0-gd
  - php7.0-imap
  - php7.0-interbase
  - php7.0-intl
  - php7.0-ldap
  - php7.0-mcrypt
  - php7.0-readline
  - php7.0-odbc
  - php7.0-pgsql
  - php7.0-pspell
  - php7.0-recode
  - php7.0-tidy
  - php7.0-xmlrpc
  - php7.0
  - php7.0-json
  - php-all-dev
  - php7.0-sybase
  - php7.0-sqlite3
  - php7.0-mysql
  - php7.0-opcache
  - php7.0-bz2
  - python-software-properties

# Vesta directories to rename
vesta_rename_dirs:
  - { src: '/usr/local/vesta/data/templates/web/php5-fpm', dst: '/usr/local/vesta/data/templates/web/php7.0-fpm' }
  - { src: '/usr/local/vesta/data/templates/web/nginx/php5-fpm', dst: '/usr/local/vesta/data/templates/web/nginx/php7.0-fpm' }
  - { src: '/usr/local/vesta/web/edit/server/php5-fpm', dst: '/usr/local/vesta/web/edit/server/php7.0-fpm'}

vesta_conf_file: '/usr/local/vesta/conf/vesta.conf'

